[application]
name = "jerry-achrich"
default_platform = "web"
out_dir = "docs"
asset_dir = "assets"

[web.app]
title = "Jerry Achrich"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
style = ["main.css", "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"]
script = []

[web.resource.dev]
script = []
